/**
 * Client logos shown on the home page. Order is curated, not alphabetical,
 * load-bearing names first so the wall reads strong on first scroll.
 */
export const CLIENTS: { slug: string; name: string }[] = [
  { slug: 'huawei', name: 'Huawei' },
  { slug: 'samsung', name: 'Samsung' },
  { slug: 'vodafone', name: 'Vodafone' },
  { slug: 'coca-cola', name: 'Coca-Cola' },
  { slug: 'microsoft', name: 'Microsoft' },
  { slug: 'hsbc', name: 'HSBC' },
  { slug: 'americana', name: 'Americana' },
  { slug: 'philips', name: 'Philips' },
  { slug: 'nissan', name: 'Nissan' },
  { slug: 'danone', name: 'Danone' },
  { slug: 'total-energies', name: 'TotalEnergies' },
  { slug: 'costa-coffee', name: 'Costa Coffee' },
  { slug: 'banque-misr', name: 'Banque Misr' },
  { slug: 'hardees', name: "Hardee's" },
  { slug: 'kfc', name: 'KFC' },
  { slug: 'zanussi', name: 'Zanussi' },
  { slug: 'unionaire', name: 'Unionaire' },
  { slug: 'etisalat', name: 'Etisalat' },
  { slug: 'eni', name: 'ENI' },
  { slug: 'sodic', name: 'Sodic' },
  { slug: 'senyorita', name: 'Senyorita' },
  { slug: 'marina-home', name: 'Marina Home' },
  { slug: 'naeem-holding', name: 'Naeem Holding' },
  { slug: 'apex-pharma', name: 'APEX Pharma' },
  { slug: 'cottonil', name: 'Cottonil' },
  { slug: 'dao-slimming', name: 'DAO' },
  { slug: 'bionime', name: 'Bionime' },
  { slug: '22-avenue', name: '22 Avenue' },
];
